CURRENCIES = (
    ('EUR', 'Euro'),
    ('USD', 'United States Dollar'),
    ('GBP', 'United Kingdom Pound'),
    ('AUD', 'Australia Dollar'),
    ('CAD', 'Canada Dollar'),
    ('BGN', 'Bulgaria Lev'),
    ('BRL', 'Brazil Real'),
    ('CHF', 'Switzerland Franc'),
    ('CNY', 'China Yuan Renminbi'),
    ('CZK', 'Czech Republic Koruna'),
    ('DKK', 'Denmark Krone'),
    ('HKD', 'Hong Kong Dollar'),
    ('HRK', 'Croatia Kuna'),
    ('HUF', 'Hungary Forint'),
    ('IDR', 'Indonesia Rupiah'),
    ('ILS', 'Israel Shekel'),
    ('INR', 'India Rupee'),
    ('JPY', 'Japan Yen'),
    ('KRW', 'Korea (South) Won'),
    ('MXN', 'Mexico Peso'),
    ('MYR', 'Malaysia Ringgit'),
    ('NOK', 'Norway Krone'),
    ('NZD', 'New Zealand Dollar'),
    ('PHP', 'Philippines Peso'),
    ('PLN', 'Poland Zloty'),
    ('RON', 'Romania New Leu'),
    ('RUB', 'Russia Ruble'),
    ('SEK', 'Sweden Krona'),
    ('SGD', 'Singapore Dollar'),
    ('THB', 'Thailand Baht'),
    ('TRY', 'Turkey Lira'),
    ('ZAR', 'South Africa Rand'),
)
