# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=9, unique=True)),
                ('sell_currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'United States Dollar'), ('GBP', 'United Kingdom Pound'), ('AUD', 'Australia Dollar'), ('CAD', 'Canada Dollar'), ('BGN', 'Bulgaria Lev'), ('BRL', 'Brazil Real'), ('CHF', 'Switzerland Franc'), ('CNY', 'China Yuan Renminbi'), ('CZK', 'Czech Republic Koruna'), ('DKK', 'Denmark Krone'), ('HKD', 'Hong Kong Dollar'), ('HRK', 'Croatia Kuna'), ('HUF', 'Hungary Forint'), ('IDR', 'Indonesia Rupiah'), ('ILS', 'Israel Shekel'), ('INR', 'India Rupee'), ('JPY', 'Japan Yen'), ('KRW', 'Korea (South) Won'), ('MXN', 'Mexico Peso'), ('MYR', 'Malaysia Ringgit'), ('NOK', 'Norway Krone'), ('NZD', 'New Zealand Dollar'), ('PHP', 'Philippines Peso'), ('PLN', 'Poland Zloty'), ('RON', 'Romania New Leu'), ('RUB', 'Russia Ruble'), ('SEK', 'Sweden Krona'), ('SGD', 'Singapore Dollar'), ('THB', 'Thailand Baht'), ('TRY', 'Turkey Lira'), ('ZAR', 'South Africa Rand')], max_length=3)),
                ('sell_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('buy_currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'United States Dollar'), ('GBP', 'United Kingdom Pound'), ('AUD', 'Australia Dollar'), ('CAD', 'Canada Dollar'), ('BGN', 'Bulgaria Lev'), ('BRL', 'Brazil Real'), ('CHF', 'Switzerland Franc'), ('CNY', 'China Yuan Renminbi'), ('CZK', 'Czech Republic Koruna'), ('DKK', 'Denmark Krone'), ('HKD', 'Hong Kong Dollar'), ('HRK', 'Croatia Kuna'), ('HUF', 'Hungary Forint'), ('IDR', 'Indonesia Rupiah'), ('ILS', 'Israel Shekel'), ('INR', 'India Rupee'), ('JPY', 'Japan Yen'), ('KRW', 'Korea (South) Won'), ('MXN', 'Mexico Peso'), ('MYR', 'Malaysia Ringgit'), ('NOK', 'Norway Krone'), ('NZD', 'New Zealand Dollar'), ('PHP', 'Philippines Peso'), ('PLN', 'Poland Zloty'), ('RON', 'Romania New Leu'), ('RUB', 'Russia Ruble'), ('SEK', 'Sweden Krona'), ('SGD', 'Singapore Dollar'), ('THB', 'Thailand Baht'), ('TRY', 'Turkey Lira'), ('ZAR', 'South Africa Rand')], max_length=3)),
                ('buy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('rate', models.DecimalField(decimal_places=7, max_digits=11)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_booked',),
            },
        ),
    ]
