# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ('date_booked',)},
        ),
    ]
